# Generated by Django 4.1.7 on 2024-05-04 19:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_review_created_at_review_reports_alter_review_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='acronym',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(blank=True, choices=[('Winter', 'Winter'), ('Monsoon', 'Monsoon')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='courses.instructor'),
        ),
        migrations.AlterField(
            model_name='review',
            name='instructor_rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
